export const SWIPE_OPTIONS = {
  platform: ["Meta", "TikTok", "YouTube", "LinkedIn", "Pinterest", "Snapchat", "X", "Other"],
  creative_format: [
    "Raw UGC",
    "Polished UGC",
    "Production Video",
    "Static",
    "Carousel",
    "Motion / Animated",
    "Screen Recording",
    "Mixed Media",
  ],
  concept: [
    "Talking Head",
    "Voiceover + B-Roll",
    "Testimonial",
    "Creator Review",
    "Founder Story",
    "Product Demo",
    "App / Software Demo",
    "Unboxing",
    "Tutorial / How-To",
    "Street Interview",
    "Podcast Clip",
    "Day in the Life",
    "Before & After",
    "Comparison",
    "Reaction",
    "Meme / Trend",
    "Product Showcase",
    "Brand Film",
    "Text-Led Video",
    "Other",
  ],
  hook: [
    "Problem Callout",
    "Bold Claim",
    "Question",
    "Audience Callout",
    "Stat / Number",
    "Warning",
    "Curiosity",
    "Before & After",
    "Social Proof",
    "POV",
    "Pattern Interrupt",
    "List",
    "Confession",
    "Authority",
    "Trend / Cultural Hook",
    "Competitor Callout",
    "Price / Offer",
    "Visual Hook",
    "No Clear Hook",
  ],
  angle_type: [
    "Pain Point",
    "Benefit / Outcome",
    "Social Proof",
    "Offer / Discount",
    "Objection Handling",
    "Education",
    "Differentiation",
    "Authority",
    "Urgency / Scarcity",
    "Cost of Inaction",
    "Ease / Convenience",
    "Speed",
    "Identity / Belonging",
    "Aspiration",
    "Risk Reversal",
    "Curiosity",
    "Humor",
    "Community",
  ],
  structure: [
    "Problem → Solution",
    "Problem → Agitate → Solution",
    "Claim → Proof",
    "Hook → Benefits → CTA",
    "Story → Lesson → Offer",
    "Before → After → How",
    "Objection → Reframe",
    "Comparison → Winner",
    "Demo → Benefit",
    "Testimonial → Result",
    "Listicle",
    "FAQ / Q&A",
    "Story Arc",
    "Reveal",
    "Other",
  ],
  business_type: [
    "Ecommerce",
    "SaaS / App",
    "B2B",
    "Local Service",
    "Marketplace",
    "Info / Education",
    "Media / Content",
    "Other",
  ],
  talent: [
    "Customer",
    "Creator",
    "Founder",
    "Employee",
    "Actor / Model",
    "Expert",
    "No Talent / Product Only",
    "Animated / AI",
  ],
  setting: [
    "Car",
    "Bedroom",
    "Bathroom / Mirror",
    "Kitchen",
    "Living Space",
    "Office / Desk",
    "Studio",
    "Outdoors",
    "Street",
    "Event / Venue",
    "Gym",
    "Retail / Store",
    "Restaurant / Cafe",
    "Screen Only",
    "Mixed",
    "Other",
  ],
  edit_style: [
    "Raw / Minimal Edit",
    "Jump Cuts",
    "Captions",
    "Kinetic Captions",
    "B-Roll Heavy",
    "Text Overlay Heavy",
    "Motion Graphics",
    "Split Screen",
    "Green Screen",
    "Fast Cut / Retention Edit",
    "Cinematic Edit",
    "Montage",
  ],
  energy: ["Calm", "Conversational", "Energetic", "High Energy"],
};

export const MULTI_SELECT_FIELDS = ["platform", "concept", "angle_type", "talent", "edit_style"];

export const REQUIRED_FIELDS = ["platform", "creative_format", "concept", "hook", "angle_type"];

export const OPTIONAL_FIELDS = ["structure", "business_type", "talent", "setting", "edit_style", "energy"];

export const FIELD_LABELS = {
  platform: "Platform",
  creative_format: "Creative Format",
  concept: "Concept",
  hook: "Hook",
  angle_type: "Message Angle",
  structure: "Structure",
  business_type: "Business Type",
  talent: "Talent",
  setting: "Setting",
  edit_style: "Edit Style",
  energy: "Energy",
  source_brand: "Brand name",
  source_url: "Source URL",
  why_it_works: "Why it works",
};

export const emptyFilters = () => ({
  ...Object.fromEntries(REQUIRED_FIELDS.map((k) => [k, MULTI_SELECT_FIELDS.includes(k) ? [] : ""])),
  ...Object.fromEntries(OPTIONAL_FIELDS.map((k) => [k, MULTI_SELECT_FIELDS.includes(k) ? [] : ""])),
});

export const isEmptyValue = (v) => (Array.isArray(v) ? v.length === 0 : !v);

export const fieldValues = (s, f) => (Array.isArray(s[f]) ? s[f] : s[f] ? [s[f]] : []);

export const needsRequiredTags = (s) => REQUIRED_FIELDS.some((f) => isEmptyValue(s[f]));