export const SWIPE_OPTIONS = {
  platform: ["Meta", "TikTok", "YouTube", "LinkedIn", "organic", "other"],
  format: [
    "UGC talking head",
    "UGC voiceover with b roll",
    "founder direct to camera",
    "customer testimonial",
    "creator review",
    "product demo",
    "screen recording or app demo",
    "street interview",
    "text over video",
    "green screen reaction",
    "split screen comparison",
    "unboxing",
    "podcast clip",
    "tutorial",
    "image carousel",
    "static image",
    "motion graphic",
    "day in the life",
    "mashup or compilation",
    "animated explainer",
    "meme",
    "ASMR",
    "AI generated",
    "cinematic brand film",
    "whiteboard",
  ],
  shot_type: [
    "Selfie Handheld",
    "Tripod Static",
    "Screen Recording",
    "Voiceover With B Roll",
    "Mixed",
  ],
  production_level: ["Phone Raw", "Phone Polished", "Semi Pro", "Studio"],
  setting: [
    "Car",
    "Bedroom",
    "Mirror Or Bathroom",
    "Kitchen",
    "Living Space",
    "Office Or Desk",
    "Studio",
    "Street Or Outdoors",
    "Event Or Venue",
    "Gym",
    "Screen Only",
    "Mixed",
  ],
  hook_type: [
    "problem callout",
    "bold claim",
    "question",
    "callout to audience",
    "stat or number",
    "negative warning",
    "curiosity gap",
    "before and after reveal",
    "social proof drop",
    "us versus them",
    "personal story open",
    "price reveal",
    "POV",
    "pattern interrupt visual",
    "list open",
    "mistake confession",
    "authority intro",
    "trend or audio hook",
    "competitor callout",
    "unboxing reveal",
  ],
  structure: [
    "problem solution",
    "listicle",
    "testimonial arc",
    "before and after",
    "demonstration",
    "story arc",
    "tutorial",
    "comparison",
    "objection handling",
    "myth bust",
    "transformation",
    "founder story",
    "data reveal",
    "FAQ",
    "reaction",
    "day in the life",
    "review roundup",
    "unboxing",
  ],
  talent: [
    "creator",
    "customer",
    "founder",
    "none or product only",
    "employee",
    "actor",
    "influencer",
    "animated or AI",
  ],
  vertical: ["ecom", "app", "B2B", "local service", "other"],
  angle_type: [
    "pain point",
    "benefit or value",
    "social proof",
    "offer or discount",
    "objection handling",
    "education",
    "differentiation",
    "authority",
    "urgency or scarcity",
    "cost of inaction",
    "ease and convenience",
    "speed of result",
    "identity and belonging",
    "aspiration",
    "risk reversal",
    "curiosity",
    "humor",
    "community",
  ],
  energy: [
    "Calm Conversational",
    "Warm And Friendly",
    "Fast And Punchy",
    "High Energy",
    "Deadpan",
    "Sincere Or Emotional",
    "Urgent",
  ],
  edit_style: [
    "Raw Single Take",
    "Jump Cuts",
    "Retention Edit",
    "Captions Only",
    "Kinetic Captions",
    "B Roll Layered",
    "Text Overlay Heavy",
    "Motion Graphics",
    "Split Screen",
    "Green Screen Reaction",
  ],
};

export const REQUIRED_FIELDS = ["platform", "format", "shot_type", "production_level"];

export const OPTIONAL_FIELDS = [
  "setting",
  "hook_type",
  "structure",
  "angle_type",
  "talent",
  "vertical",
  "energy",
  "edit_style",
];

export const FIELD_LABELS = {
  source_brand: "Source brand",
  source_url: "Source URL",
  platform: "Platform",
  format: "Format",
  shot_type: "Shot Type",
  production_level: "Production Level",
  setting: "Setting",
  hook_type: "Hook type",
  structure: "Structure",
  talent: "Talent",
  vertical: "Vertical",
  angle_type: "Message Angle",
  energy: "Energy",
  edit_style: "Edit Style",
  why_it_works: "Why it works",
};

export const ENUM_COLS = [
  "platform",
  "format",
  "shot_type",
  "production_level",
  "setting",
  "hook_type",
  "talent",
  "vertical",
  "angle_type",
  "energy",
  "edit_style",
];
export const MULTI_COLS = ["structure"];
export const TEXT_COLS = ["source_brand", "source_url", "why_it_works"];

export const needsRequiredTags = (s) => REQUIRED_FIELDS.some((f) => !s[f]);